server:
  port: 8000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      sla:
        findByUser: 100ms,1000ms, 5000ms, 10000ms
      percentiles-histogram:
        - findByUser : true