apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      containers:
      - image: k1p3r/otus-homework-3-final
        name: otus-homework-3
        ports:
          - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8000
          initialDelaySeconds: 20
          timeoutSeconds: 2
          periodSeconds: 8
          failureThreshold: 1
        resources: {}
        env:
          - name: DATABASE_CONNETION_URL
            value: "jdbc:postgresql://postgres.default.svc.cluster.local:5432/myapp"
          - name: DATABASE_USERNAME
            value: myuser
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgresql-password
                name: postgres
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: my-demo-config-map
                key: ENVIROMENT

status: {}
