apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-demo-monitor
  labels:
    app: demo
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: demo
  endpoints:
    - interval: 15s
      port: web
      path: /actuator/prometheus
