{
 "title": "MyDashBoard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "ingress-nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "rps by bucket",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{}[1m]))",
       "legendFormat": "{{value}}"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "rate(nginx_ingress_controller_nginx_process_requests_total{}[1m])"
      }
     ]
    },
    {
     "title": "Error rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "rate(nginx_ingress_controller_request_duration_seconds_count{status=\"500\"}[1m])"
      }
     ]
    },
    {
     "title": "quantiles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{}[1m])))",
       "legendFormat": "0.5"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{}[1m])))",
       "legendFormat": ".95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{}[1m])))",
       "legendFormat": ".99"
      }
     ]
    }
   ]
  },
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "findByUser Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(rate(findByUser_seconds{quantile=\"0.99\"}[1m]))",
     "legendFormat": ".99"
    },
    {
     "expr": "sum(rate(findByUser_seconds{quantile=\"0.95\"}[1m]))",
     "legendFormat": ".95"
    },
    {
     "expr": "sum(rate(findByUser_seconds{quantile=\"0.9\"}[1m]))",
     "legendFormat": ".9"
    },
    {
     "expr": "sum(rate(findByUser_seconds{quantile=\"0.5\"}[1m]))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    { "expr": "max(findByUser_seconds_max{})", "legendFormat": "findByUser" }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(findByUser_seconds_count{}[1m]))",
     "legendFormat": "findByUser"
    }
   ]
  },
  {
   "title": "ErrorRate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(findByUser_seconds_count{exception=\"RuntimeException\"}[1m]))",
     "legendFormat": "findByUserErrorRate"
    }
   ]
  }
 ]
}